name: Rspec

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.6.47
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: staffomatic_user_management_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Verify MySQL connection from host
        run: |
          sudo apt-get install -y mysql-client
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -e "SHOW DATABASES"
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
      - name: Install dependent libraries
        run: |
          sudo apt-get update
          sudo apt-get -yqq install mysql-client libmysqlclient-dev fontconfig libfreetype6 libjpeg-turbo8 libpng16-16 libx11-6 libxcb1 libxext6 libxrender1 xfonts-75dpi xfonts-base
          sudo apt-get install -f
      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gemsrails6-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gemsrails6-
      - name: Bundle install
        env:
          DATABASE_URL: mysql2://root:@127.0.0.1/staffomatic_user_management_test
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_TEST_KEY }}
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Setup the database
        env:
          DATABASE_URL: mysql2://root:@127.0.0.1/staffomatic_user_management_test
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_TEST_KEY }}
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load
      - name: Run RSpec
        env:
          DATABASE_URL: mysql2://root:@127.0.0.1/staffomatic_user_management_test
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_TEST_KEY }}
        run: bundle exec rspec
